version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - nginx
      - maintenance-service
      - security-service
      - process-service

  maintenance-service:
    build: ./maintenance-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - sqlserver

  security-service:
    build: ./security-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - sqlserver

  process-service:
    build: ./process-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      - sqlserver

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "D123s456"
    ports:
      - "1434:1433"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - maintenance-service
      - security-service
      - process-service
